import os
import sys
import subprocess
from pathlib import Path

REQUIRED_VARS = [
    ("TELEGRAM_BOT_TOKEN", "Token del bot de Telegram"),
    ("STORAGE_DIR", "Carpeta base de almacenamiento (puedes usar /mnt/vault)"),
    ("META_LOG", "Ruta al archivo JSON de metadatos"),
    ("GEMINI_API_KEY", "API Key de Google Gemini (opcional para IA)"),
]

DEFAULTS = {
    "STORAGE_DIR": "./vault_storage",
    "META_LOG": "./vault_storage/metadata.jsonl",
    "MAX_BYTES": "0",
    "ALLOW_COMPRESSED_PHOTOS": "true",
    "DEFAULT_CONTEXT": "default",
    "AI_MODEL": "gemini-3.1-flash-lite-preview",
}

def check_dependencies():
    print("\n--- Verificando Dependencias ---")
    req_file = Path("requirements.txt")
    if not req_file.exists():
        print("❌ Error: No se encontró requirements.txt")
        return False
    
    try:
        # Intentar verificar sin instalar nada primero
        with open(req_file, "r") as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith("#"):
                    continue
                pkg = line.split("==")[0].split(">")[0].strip()
                try:
                    __import__(pkg.replace("-", "_"))
                except ImportError:
                    print(f"⚠️  Falta: {pkg}. Reinstalando...")
                    subprocess.check_call([sys.executable, "-m", "pip", "install", "-r", "requirements.txt"])
                    break
        print("✅ Todas las librerías están instaladas.")
        return True
    except Exception as e:
        print(f"❌ Error al verificar dependencias: {e}")
        return False

def sync_env():
    print("\n--- Configuración de Entorno (.env) ---")
    env_path = Path(".env")
    example_path = Path(".env.example")
    
    existing_vars = {}
    if env_path.exists():
        print("ℹ️  Archivo .env detectado. Leyendo configuración actual...")
        with open(env_path, "r", encoding="utf-8") as f:
            for line in f:
                if "=" in line and not line.strip().startswith("#"):
                    k, v = line.strip().split("=", 1)
                    existing_vars[k.strip()] = v.strip()
    else:
        print("ℹ️  No se encontró .env. Creando uno nuevo basado en el ejemplo...")

    new_vars = existing_vars.copy()
    updated = False

    # Fusionar con example y pedir lo que falte
    for key, description in REQUIRED_VARS:
        if key not in new_vars or not new_vars[key]:
            default = DEFAULTS.get(key, "")
            val = input(f"❓ [{key}] {description} (Default: {default}): ").strip()
            new_vars[key] = val if val else default
            updated = True
    
    # Asegurar que existan todos los defaults del example que no estén en new_vars
    if example_path.exists():
        with open(example_path, "r", encoding="utf-8") as f:
            for line in f:
                if "=" in line and not line.strip().startswith("#"):
                    k, v = line.strip().split("=", 1)
                    k = k.strip()
                    if k not in new_vars:
                        new_vars[k] = v.strip()
                        updated = True

    if updated or not env_path.exists():
        print("💾 Guardando cambios en .env...")
        # Intentar mantener comentarios si fuera un fusionador pro,
        # pero por ahora simplemente escribimos el diccionario de forma limpia.
        with open(env_path, "w", encoding="utf-8") as f:
            f.write("# Vault Ingestor - Autogenerated .env\n")
            for k, v in new_vars.items():
                f.write(f"{k}={v}\n")
        print("✅ Archivo .env actualizado.")
    else:
        print("✅ El archivo .env ya está completo.")

def check_mount_point(storage_path):
    path = Path(storage_path).resolve()
    print(f"\n--- Verificando Almacenamiento: {path} ---")
    if not path.exists():
        print(f"⚠️  Aviso: La carpeta {path} no existe. Se intentará crear al arrancar.")
    
    # En Linux podemos checkear si es un mount
    if hasattr(os.path, 'ismount') and os.path.ismount(str(path)):
        print("✅ Detectado como punto de montaje activo.")
    elif str(path).startswith("/mnt/") or str(path).startswith("/media/"):
        print("⚠️  ATENCIÓN: La ruta parece un disco externo pero NO está montado (o no estoy en Linux).")
        print("   Asegúrate de que el disco esté conectado.")

def main():
    print("==========================================")
    print("   Vault Ingestor - Smart Setup Wizard")
    print("==========================================")
    
    if not check_dependencies():
        sys.exit(1)
        
    sync_env()
    
    # Recargar env para ver la ruta
    from dotenv import load_dotenv
    load_dotenv()
    storage_dir = os.getenv("STORAGE_DIR", "./vault_storage")
    check_mount_point(storage_dir)

    print("\n🎉 Configuración completada correctamente.")
    print("Puedes arrancar el servicio con: python app.py")
    print("O configurar systemd usando el archivo vault_ingestor.service")

if __name__ == "__main__":
    main()
