import os
import sys
import subprocess
from pathlib import Path
import tkinter as tk
from tkinter import simpledialog, messagebox

# Variables específicas del Core
REQUIRED_VARS = [
    ("STORAGE_DIR", "Carpeta base de almacenamiento (ej: ./vault_storage)"),
    ("META_LOG", "Ruta al archivo JSON de metadatos (ej: ./vault_storage/metadata.jsonl)"),
]

DEFAULTS = {
    "STORAGE_DIR": "./vault_storage",
    "META_LOG": "./vault_storage/metadata.jsonl",
    "API_HOST": "127.0.0.1",
    "API_PORT": "8081",
}

def check_dependencies():
    print("\n--- Verificando Dependencias ---")
    req_file = Path(__file__).resolve().parent.parent / "requirements.txt"
    if not req_file.exists():
        print("❌ Error: No se encontró requirements.txt en el directorio padre.")
        return False
    
    try:
        subprocess.check_call([sys.executable, "-m", "pip", "install", "-r", str(req_file)])
        print("✅ Todas las librerías están instaladas.")
        return True
    except Exception as e:
        print(f"❌ Error al instalar dependencias: {e}")
        return False

def sync_env():
    root = tk.Tk()
    root.withdraw()
    
    env_path = Path(__file__).resolve().parent.parent / ".env"
    
    existing_vars = {}
    if env_path.exists():
        with open(env_path, "r", encoding="utf-8") as f:
            for line in f:
                if "=" in line and not line.strip().startswith("#"):
                    k, v = line.strip().split("=", 1)
                    existing_vars[k.strip()] = v.strip()

    new_vars = existing_vars.copy()
    updated = False

    # Pedir lo que falte
    for key, description in REQUIRED_VARS:
        if key not in new_vars or not new_vars[key]:
            default = DEFAULTS.get(key, "")
            
            # Usar Tkinter para pedir la entrada
            val = simpledialog.askstring(
                f"Configuración de {key}", 
                f"{description}\n(Dejar en blanco para usar el valor por defecto: {default})",
                initialvalue=default
            )
            
            # Si val es None (cancelado) o string vacío, usar el default
            if val is None or str(val).strip() == "":
                new_vars[key] = default
            else:
                new_vars[key] = val.strip()
            updated = True
    
    # Asegurar que existan todos los defaults
    for k, v in DEFAULTS.items():
        if k not in new_vars:
            new_vars[k] = v
            updated = True

    if updated or not env_path.exists():
        with open(env_path, "w", encoding="utf-8") as f:
            f.write("# Vault Ingestor Desktop - Autogenerated .env\n")
            for k, v in new_vars.items():
                f.write(f"{k}={v}\n")
        messagebox.showinfo("Configuración completada", "✅ Archivo .env configurado correctamente.\n\nYa puedes iniciar el Launcher.")
    else:
        messagebox.showinfo("Configuración", "✅ El archivo .env ya estaba completo. No se hicieron cambios.")
        
    root.destroy()

def main():
    print("==========================================")
    print("   Vault Ingestor - Desktop Setup Wizard")
    print("==========================================")
    
    # El launcher de escritorio ya instala dependencias, pero lo mantenemos por consistencia
    if not check_dependencies():
        # Fallback silencioso si falla, lo importante en el setup es el env
        pass
        
    sync_env()

if __name__ == "__main__":
    main()
