import os
import sys
import subprocess
from pathlib import Path

# Variables específicas del Core
REQUIRED_VARS = [
    ("STORAGE_DIR", "Carpeta base de almacenamiento (ej: ./vault_storage)"),
    ("META_LOG", "Ruta al archivo JSON de metadatos (ej: ./vault_storage/metadata.jsonl)"),
]

DEFAULTS = {
    "STORAGE_DIR": "./vault_storage",
    "META_LOG": "./vault_storage/metadata.jsonl",
    "API_HOST": "0.0.0.0",
    "API_PORT": "8000",
}

def check_dependencies():
    print("\n--- Verificando Dependencias ---")
    req_file = Path("requirements.txt")
    if not req_file.exists():
        print("❌ Error: No se encontró requirements.txt")
        return False
    
    try:
        subprocess.check_call([sys.executable, "-m", "pip", "install", "-r", "requirements.txt"])
        print("✅ Todas las librerías están instaladas.")
        return True
    except Exception as e:
        print(f"❌ Error al instalar dependencias: {e}")
        return False

def sync_env():
    print("\n--- Configuración de Entorno (.env) ---")
    env_path = Path(".env")
    
    existing_vars = {}
    if env_path.exists():
        print("ℹ️  Archivo .env detectado. Leyendo configuración actual...")
        with open(env_path, "r", encoding="utf-8") as f:
            for line in f:
                if "=" in line and not line.strip().startswith("#"):
                    k, v = line.strip().split("=", 1)
                    existing_vars[k.strip()] = v.strip()
    else:
        print("ℹ️  No se encontró .env. Creando uno nuevo...")

    new_vars = existing_vars.copy()
    updated = False

    # Pedir lo que falte
    for key, description in REQUIRED_VARS:
        if key not in new_vars or not new_vars[key]:
            default = DEFAULTS.get(key, "")
            val = input(f"❓ [{key}] {description} (Default: {default}): ").strip()
            new_vars[key] = val if val else default
            updated = True
    
    # Asegurar que existan todos los defaults
    for k, v in DEFAULTS.items():
        if k not in new_vars:
            new_vars[k] = v
            updated = True

    if updated or not env_path.exists():
        print("💾 Guardando cambios en .env...")
        with open(env_path, "w", encoding="utf-8") as f:
            f.write("# Vault Ingestor Core - Autogenerated .env\n")
            for k, v in new_vars.items():
                f.write(f"{k}={v}\n")
        print("✅ Archivo .env actualizado.")
    else:
        print("✅ El archivo .env ya está completo.")

def main():
    print("==========================================")
    print("   Vault Ingestor - Core Setup Wizard")
    print("==========================================")
    
    if not check_dependencies():
        sys.exit(1)
        
    sync_env()
    
    print("\n🎉 Configuración completada correctamente.")
    print("Puedes arrancar el servidor API con: python app.py")

if __name__ == "__main__":
    main()
